### PR TITLE
Update default layout card and add blank version

### PR DESCRIPTION
**Pull request by TheBaronHimself**

### CODE REVIEW

**Comment by obra** [comment]
What are the changes to the 'default' layout card here?

Thanks!

**Comment by TheBaronHimself** [comment]
PDF: Sanitised the file/removed metadata. I consider it good practice and didn't do it when I sent it to you for printing as I didn't think it was going to end up public. I may also have forgotten after the all-nighter at the time ;). 

The SVG I just optimised; it's smaller now.

**Comment by obra** [comment]
Can you repush with commit messages describing the changes and not changing
the filenames for the layout cards? That'll help keep the history easier to
understand.

Thanks!

**Comment by TheBaronHimself** [comment]
In that case I'd rather the date strings were removed entirely. They'll be pretty useless, anyway.

**Comment by obra** [comment]
Sure, though the rename should be a separate git commit.

-j

**Pull request closed without merging**
